/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  safelist: [
    "bg-black",
    "text-white",
    "min-h-screen",
    "flex",
    "items-center",
    "justify-center",
    "p-4",
    "text-center",
    "font-bold",
    "text-4xl",
    "mb-4",
    "bg-gradient-to-r",
    "from-blue-600",
    "to-purple-600",
    "rounded-full",
    "px-8",
    "py-3",
    "hover:scale-105",
    "transition-all",
    "duration-300",
    "shadow-lg",
    "hover:shadow-xl",
    "transform",
    "scale-105",
    "bg-white",
    "text-black",
    "hover:bg-gray-100",
    "w-5",
    "h-5",
    "ml-2",
    "mr-2",
    "gap-3",
    "inline-flex",
    "align-items",
    "whitespace-nowrap",
    "cursor-pointer",
    "focus-visible:outline-none",
    "focus-visible:ring-2",
    "focus-visible:ring-ring",
    "focus-visible:ring-offset-2",
    "disabled:pointer-events-none",
    "disabled:opacity-50",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        // New Medspa Theme Colors
        "medspa-primary": "#367588",
        "medspa-secondary": "#2c5f6b",
        "medspa-accent": "#367588",
        "medspa-accent-24": "rgba(54, 117, 136, 0.24)",
        "medspa-bg": "#FFFFFF",
        "medspa-bg-secondary": "#F3F4F6",
        "medspa-text-primary": "#000000",
        "medspa-text-secondary": "#6B7280",
      },
      animation: {
        "fade-in": "fadeIn 0.5s ease-in-out",
        "slide-up": "slideUp 0.5s ease-out",
        "scale-in": "scaleIn 0.3s ease-out",
        float: "float 6s ease-in-out infinite",
        "pulse-slow": "pulse 3s ease-in-out infinite",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        slideUp: {
          "0%": { transform: "translateY(20px)", opacity: "0" },
          "100%": { transform: "translateY(0)", opacity: "1" },
        },
        scaleIn: {
          "0%": { transform: "scale(0.9)", opacity: "0" },
          "100%": { transform: "scale(1)", opacity: "1" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-20px)" },
        },
      },
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
      boxShadow: {
        "3xl": "0 35px 60px -12px rgba(0, 0, 0, 0.25)",
        glow: "0 0 20px rgba(59, 130, 246, 0.3)",
        "glow-lg": "0 0 40px rgba(59, 130, 246, 0.4)",
      },
    },
  },
  plugins: [],
};
